# Predictivo-Cli-Camion (ex Solo_Tabla_menuDatos.ipynb)

In [1]:
# Preliminares

import pandas as pd
import numpy as np
import re

In [2]:
# lectura de datos 
merged_df = pd.read_excel("../Limpia/merged_df.xlsx")

In [3]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22399 entries, 0 to 22398
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CODIGO            22399 non-null  int64
 1   PROYECTO          22399 non-null  object
 2   NOMCLI            22399 non-null  object
 3   Duracion          22399 non-null  float64
 4   Tiempo_de_Inicio  22399 non-null  datetime64[ns]
 5   UBICACIÓN         22399 non-null  object
 6   Numero_de_placa   22399 non-null  object
 7   LATITUD           22399 non-null  float64
 8   LONGITUD          22399 non-null  float64
 9   camion_x          22399 non-null  float64
 10  camion_y          22399 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(1), object(4)
memory usage: 1.9+ MB

In [4]:
merged_df.head()

,CODIGO,PROYECTO,NOMCLI,Duracion,Tiempo_de_Inicio,UBICACIÓN,Numero_de_placa,LATITUD,LONGITUD,camion_x,camion_y
0,11975,Ruta Dario Lunes,"DUNAS,PARQUE DEL PLATA NORTE",8.37,2024-11-22 08:17:56,"Marcador 134\nlat/lng: (-34.74643,-55.71194)\n...",PEUGEOTAVG9758,-34.74643,-55.71194,-34.746347,-55.711935
1,11975,Ruta Dario Lunes,"DUNAS,PARQUE DEL PLATA NORTE",7.58,2024-11-25 08:07:49,"Marcador 134\nlat/lng: (-34.74643,-55.71194)\n...",PEUGEOTAVG9758,-34.74643,-55.71194,-34.746390,-55.711865
2,11975,Ruta Dario Lunes,"DUNAS,PARQUE DEL PLATA NORTE",6.85,2024-11-27 08:21:35,"Marcador 134\nlat/lng: (-34.74643,-55.71194)\n...",PEUGEOTAVG9758,-34.74643,-55.71194,-34.746450,-55.711880
3,11975,Ruta Dario Lunes,"DUNAS,PARQUE DEL PLATA NORTE",8.33,2024-11-29 08:13:52,"Marcador 134\nlat/lng: (-34.74643,-55.71194)\n...",PEUGEOTAVG9758,-34.74643,-55.71194,-34.746465,-55.711879
4,11975,Ruta Dario Lunes,"DUNAS,PARQUE DEL PLATA NORTE",6.55,2024-11-04 12:49:20,"Marcador 134\nlat/lng: (-34.74643,-55.71194)\n...",BYD1004,-34.74643,-55.71194,-34.745840,-55.712427

### Transformo algunas cosas para que se vea Tabla_1

In [5]:
#  Ubica Camion 
merged_df['Ubicacion_Camion'] = merged_df.apply(
    lambda row: f"https://www.google.com/maps?q={row['camion_x']},{row['camion_y']}", axis=1
)

In [6]:
#  Ubicacion_Cliente con  Google Maps 
merged_df['Ubicacion_Cliente'] = merged_df.apply(
    lambda row: f"https://www.google.com/maps?q={row['LATITUD']},{row['LONGITUD']}", axis=1
)

In [7]:
# Recupero dia y hora 
merged_df['Dia_camion_estac'] = merged_df['Tiempo_de_Inicio'].dt.date
merged_df['Hora_camion_desde'] = merged_df['Tiempo_de_Inicio'].dt.time

In [8]:
# Tabla Final 
Tabla_Final = merged_df[['Numero_de_placa', 'PROYECTO', 'Dia_camion_estac', 'Hora_camion_desde', 
                         'Ubicacion_Camion', 'Duracion', 'CODIGO', 'NOMCLI', 'Ubicacion_Cliente']]

In [9]:
Tabla_Final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22399 entries, 0 to 22398
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Numero_de_placa    22399 non-null  object
 1   PROYECTO           22399 non-null  object
 2   Dia_camion_estac   22399 non-null  object
 3   Hora_camion_desde  22399 non-null  object
 4   Ubicacion_Camion   22399 non-null  object
 5   Duracion           22399 non-null  float64
 6   CODIGO             22399 non-null  int64
 7   NOMCLI             22399 non-null  object
 8   Ubicacion_Cliente  22399 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.5+ MB

In [10]:
# Formatear fecha 
Tabla_Final['Dia_camion_estac'] = pd.to_datetime(Tabla_Final['Dia_camion_estac']).dt.strftime('%d-%m-%Y')

C:\RTEMP\ipykernel_11716\3411140125.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['Dia_camion_estac'] = pd.to_datetime(Tabla_Final['Dia_camion_estac']).dt.strftime('%d-%m-%Y')

In [11]:

# Formatear hora 
#Tabla_Final['Dia_camion_estac'] = pd.to_datetime(Tabla_Final['Dia_camion_estac']).dt.strftime('%d-%m-%Y')

Tabla_Final['Hora_camion_desde'] = Tabla_Final['Hora_camion_desde'].astype(str).str[:5]  # Mantiene solo 'HH_MM'

# Mostrar el resultado
print(Tabla_Final[['Dia_camion_estac', 'Hora_camion_desde']])

      Dia_camion_estac Hora_camion_desde
0           22-11-2024             08:17
1           25-11-2024             08:07
2           27-11-2024             08:21
3           29-11-2024             08:13
4           04-11-2024             12:49
...                ...               ...
22394       30-01-2025             09:11
22395       01-02-2025             09:13
22396       04-02-2025             10:08
22397       06-02-2025             09:28
22398       08-02-2025             09:29

[22399 rows x 2 columns]

C:\RTEMP\ipykernel_11716\1858070140.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['Hora_camion_desde'] = Tabla_Final['Hora_camion_desde'].astype(str).str[:5]  # Mantiene solo 'HH_MM'

In [12]:
# Check 

Tabla_Final.head()

,Numero_de_placa,PROYECTO,Dia_camion_estac,Hora_camion_desde,Ubicacion_Camion,Duracion,CODIGO,NOMCLI,Ubicacion_Cliente
0,PEUGEOTAVG9758,Ruta Dario Lunes,22-11-2024,08:17,"https://www.google.com/maps?q=-34.746347,-55.7...",8.37,11975,"DUNAS,PARQUE DEL PLATA NORTE","https://www.google.com/maps?q=-34.74643,-55.71194"
1,PEUGEOTAVG9758,Ruta Dario Lunes,25-11-2024,08:07,"https://www.google.com/maps?q=-34.74639,-55.71...",7.58,11975,"DUNAS,PARQUE DEL PLATA NORTE","https://www.google.com/maps?q=-34.74643,-55.71194"
2,PEUGEOTAVG9758,Ruta Dario Lunes,27-11-2024,08:21,"https://www.google.com/maps?q=-34.74645,-55.71188",6.85,11975,"DUNAS,PARQUE DEL PLATA NORTE","https://www.google.com/maps?q=-34.74643,-55.71194"
3,PEUGEOTAVG9758,Ruta Dario Lunes,29-11-2024,08:13,"https://www.google.com/maps?q=-34.746465,-55.7...",8.33,11975,"DUNAS,PARQUE DEL PLATA NORTE","https://www.google.com/maps?q=-34.74643,-55.71194"
4,BYD1004,Ruta Dario Lunes,04-11-2024,12:49,"https://www.google.com/maps?q=-34.74584,-55.71...",6.55,11975,"DUNAS,PARQUE DEL PLATA NORTE","https://www.google.com/maps?q=-34.74643,-55.71194"

In [13]:

# Convertir las columnas a string en caso de que estén en formato bytes
Tabla_Final['Ubicacion_Camion'] = Tabla_Final['Ubicacion_Camion'].astype(str)
Tabla_Final['Ubicacion_Cliente'] = Tabla_Final['Ubicacion_Cliente'].astype(str)

# Definir la función para extraer coordenadas de Ubicacion_Camion
def extract_coordinates_from_camion(url):
    match = re.search(r'(-?\d+\.\d+),(-?\d+\.\d+)', url)
    if match:
        return float(match.group(1)), float(match.group(2))
    else:
        return None, None

# Definir la función para extraer coordenadas de Ubicacion_Cliente
def extract_coordinates_from_cliente(url):
    # Intentar encontrar el formato con o sin paréntesis, permitiendo espacios en blanco
    match = re.search(r'\(?\s*(-?\d+\.\d+)\s*,\s*(-?\d+\.\d+)\s*\)?', url)
    if match:
        return float(match.group(1)), float(match.group(2))
    else:
        return None, None

# Aplicar las funciones para extraer las coordenadas en nuevas columnas
Tabla_Final[['lat_camion', 'lon_camion']] = Tabla_Final['Ubicacion_Camion'].apply(
    lambda x: pd.Series(extract_coordinates_from_camion(x))
)
Tabla_Final[['lat_cliente', 'lon_cliente']] = Tabla_Final['Ubicacion_Cliente'].apply(
    lambda x: pd.Series(extract_coordinates_from_cliente(x))
)

# Calcular la distancia Haversine
def haversine(lat1, lon1, lat2, lon2):
    # Verificar que ninguna coordenada sea None
    if None in [lat1, lon1, lat2, lon2]:
        return np.nan  # Devuelve NaN si falta alguna coordenada
    R = 6371000  # Radio de la Tierra en metros
    phi1, phi2 = np.radians(lat1), np.radians(lat2)
    delta_phi = np.radians(lat2 - lat1)
    delta_lambda = np.radians(lon2 - lon1)
    
    a = np.sin(delta_phi / 2) ** 2 + np.cos(phi1) * np.cos(phi2) * np.sin(delta_lambda / 2) ** 2
    c = 2 * np.arctan2(np.sqrt(a), np.sqrt(1 - a))
    
    return R * c  # Distancia en metros

# Calcular la distancia en metros y agregarla en una nueva columna
Tabla_Final['distancia_en_Metro'] = Tabla_Final.apply(
    lambda row: haversine(row['lat_camion'], row['lon_camion'], row['lat_cliente'], row['lon_cliente']), axis=1
)

# Revisar los primeros valores para confirmar el cálculo
print(Tabla_Final[['lat_camion', 'lon_camion', 'lat_cliente', 'lon_cliente', 'distancia_en_Metro']].head())

C:\RTEMP\ipykernel_11716\843401648.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['Ubicacion_Camion'] = Tabla_Final['Ubicacion_Camion'].astype(str)
C:\RTEMP\ipykernel_11716\843401648.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['Ubicacion_Cliente'] = Tabla_Final['Ubicacion_Cliente'].astype(str)
C:\RTEMP\ipykernel_11716\843401648.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final[['lat_camion', 'lon_camion']] = Tabla_Final['Ubicacion_Camion'].apply(
C:\RTEMP\ipykernel_11716\843401648.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final[['lat_camion', 'lon_camion']] = Tabla_Final['Ubicacion_Camion'].apply(
C:\RTEMP\ipykernel_11716\843401648.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final[['lat_cliente', 'lon_cliente']] = Tabla_Final['Ubicacion_Cliente'].apply(
C:\RTEMP\ipykernel_11716\843401648.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final[['lat_cliente', 'lon_cliente']] = Tabla_Final['Ubicacion_Cliente'].apply(

   lat_camion  lon_camion  lat_cliente  lon_cliente  distancia_en_Metro
0  -34.746347  -55.711935    -34.74643    -55.71194            9.240478
1  -34.746390  -55.711865    -34.74643    -55.71194            8.169452
2  -34.746450  -55.711880    -34.74643    -55.71194            5.915928
3  -34.746465  -55.711879    -34.74643    -55.71194            6.797710
4  -34.745840  -55.712427    -34.74643    -55.71194           79.271038

C:\RTEMP\ipykernel_11716\843401648.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['distancia_en_Metro'] = Tabla_Final.apply(

In [14]:
 #Verificar el resultado
Tabla_Final[['Numero_de_placa', 'Ubicacion_Camion', 'Ubicacion_Cliente', 'distancia_en_Metro']].head(10)

,Numero_de_placa,Ubicacion_Camion,Ubicacion_Cliente,distancia_en_Metro
0,PEUGEOTAVG9758,"https://www.google.com/maps?q=-34.746347,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",9.240478
1,PEUGEOTAVG9758,"https://www.google.com/maps?q=-34.74639,-55.71...","https://www.google.com/maps?q=-34.74643,-55.71194",8.169452
2,PEUGEOTAVG9758,"https://www.google.com/maps?q=-34.74645,-55.71188","https://www.google.com/maps?q=-34.74643,-55.71194",5.915928
3,PEUGEOTAVG9758,"https://www.google.com/maps?q=-34.746465,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",6.797710
4,BYD1004,"https://www.google.com/maps?q=-34.74584,-55.71...","https://www.google.com/maps?q=-34.74643,-55.71194",79.271038
5,BYD1004,"https://www.google.com/maps?q=-34.745877,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",78.837718
6,BYD1004,"https://www.google.com/maps?q=-34.746879,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",131.374284
7,BYD1004,"https://www.google.com/maps?q=-34.745858,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",80.608551
8,BYD1004,"https://www.google.com/maps?q=-34.74586,-55.71...","https://www.google.com/maps?q=-34.74643,-55.71194",78.343368
9,BYD1004,"https://www.google.com/maps?q=-34.745892,-55.7...","https://www.google.com/maps?q=-34.74643,-55.71194",79.858357

In [15]:
# Redondear 'distancia_en_Metro' a dos decimales
Tabla_Final['distancia_en_Metro'] = Tabla_Final['distancia_en_Metro'].round(2)

# Eliminar las columnas de coordenadas solo si existen
columns_to_drop = ['lat_camion', 'lon_camion', 'lat_cliente', 'lon_cliente']
Tabla_Final = Tabla_Final.drop(columns=[col for col in columns_to_drop if col in Tabla_Final.columns])

C:\RTEMP\ipykernel_11716\1252187208.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Tabla_Final['distancia_en_Metro'] = Tabla_Final['distancia_en_Metro'].round(2)

In [16]:
# Verificar el resultado final
Tabla_Final.tail()

,Numero_de_placa,PROYECTO,Dia_camion_estac,Hora_camion_desde,Ubicacion_Camion,Duracion,CODIGO,NOMCLI,Ubicacion_Cliente,distancia_en_Metro
22394,PARTNER 4251,💲Creditos Administracion,30-01-2025,09:11,"https://www.google.com/maps?q=-34.780749,-55.8...",21.62,12450,Efeta SRL,https://www.google.com/maps?q=-34.780645309208...,20.28
22395,PARTNER 4251,💲Creditos Administracion,01-02-2025,09:13,"https://www.google.com/maps?q=-34.78077,-55.83...",14.40,12450,Efeta SRL,https://www.google.com/maps?q=-34.780645309208...,21.70
22396,PARTNER 4251,💲Creditos Administracion,04-02-2025,10:08,"https://www.google.com/maps?q=-34.780809,-55.8...",23.03,12450,Efeta SRL,https://www.google.com/maps?q=-34.780645309208...,22.93
22397,PARTNER 4251,💲Creditos Administracion,06-02-2025,09:28,"https://www.google.com/maps?q=-34.780865,-55.8...",34.58,12450,Efeta SRL,https://www.google.com/maps?q=-34.780645309208...,26.14
22398,PARTNER 4251,💲Creditos Administracion,08-02-2025,09:29,"https://www.google.com/maps?q=-34.78077,-55.83...",22.95,12450,Efeta SRL,https://www.google.com/maps?q=-34.780645309208...,19.35

In [17]:
Tabla_Final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22399 entries, 0 to 22398
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Numero_de_placa     22399 non-null  object
 1   PROYECTO            22399 non-null  object
 2   Dia_camion_estac    22399 non-null  object
 3   Hora_camion_desde   22399 non-null  object
 4   Ubicacion_Camion    22399 non-null  object
 5   Duracion            22399 non-null  float64
 6   CODIGO              22399 non-null  int64
 7   NOMCLI              22399 non-null  object
 8   Ubicacion_Cliente   22399 non-null  object
 9   distancia_en_Metro  22399 non-null  float64
dtypes: float64(2), int64(1), object(7)
memory usage: 1.7+ MB

In [18]:
Tabla_Final = Tabla_Final.rename(columns={"distancia_en_Metro": "distancia_predictiva"})

In [19]:
# Step 5: Export Tabla_Final to Excel
Tabla_Final.to_excel('../Limpia/Tabla_Final_menuDatos.xlsx', index=False)